baseURL: 'https://covidapibs.com/'
languageCode: en-uk
title: COVID-19 API Bahamas

upload_dir: static/uploads
public_path: /uploads

disableKinds:
  - taxonomy
  - taxonomyTerm
  - categories

outputs:
  page:
    - json
  section:
    - json
  home:
    - HTML