baseURL: 'https://apibahamas.app/'
languageCode: en-uk
title: COVID-19 API Bahamas
assetDir: 
  - "assets"

upload_dir: static/uploads
public_path: /uploads

disableKinds:
  - taxonomy
  - taxonomyTerm
  - categories

outputs:
  page:
    - HTML
    - json
  section:
    - HTML
    - json
  home:
    - HTML

# params:
#   dateFormat: 02 Jan 2006

